logging:
  level: "info"
  file: "app.log"

database:
  development:
    host: localhost
    port: 5432
    user: dev_user
    password: dev_password
    dbname: myapp_dev
    sslmode: disable
    max_open_conns: 25
    max_idle_conns: 5
    conn_max_lifetime: 1h
    conn_max_idle_time: 15m

  production:
    host: ${DB_HOST}
    port: ${DB_PORT}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    dbname: ${DB_NAME}
    sslmode: require
    max_open_conns: 100
    max_idle_conns: 10
    conn_max_lifetime: 30m
    conn_max_idle_time: 5m

  test:
    host: localhost
    port: 5432
    user: test_user
    password: test_password
    dbname: myapp_test
    sslmode: disable
    max_open_conns: 10
    max_idle_conns: 2
    conn_max_lifetime: 1h
    conn_max_idle_time: 15m
